"""Deterministic flow -> Python codegen (#146, dev item 6).

A developer presses Copy and leaves with a runnable scaffold of THEIR flow:
one function per block, wired in graph order, grounded in the catalog's
cheat-sheet notes and doc links. No LLM writes this file (D3): the generator
is a pure function of the workflow + catalog, so the same flow always yields
the same code.

Safety blocks become guard functions that raise instead of letting money move;
event blocks become webhook handler stubs; custom code blocks (#147) land
verbatim where the dev placed them.
"""

from __future__ import annotations

import re
from collections import deque

from ..ir.models import Node, Workflow
from ..providers import default_catalog
from ..providers.base import Catalog

# Documented endpoint per node type (Monnify API cheat sheet / developers
# .monnify.com). Codegen-local on purpose: the catalog stays transport-neutral.
_ENDPOINTS: dict[str, tuple[str, str]] = {
    "monnify.initialize_transaction": ("POST", "/api/v1/merchant/transactions/init-transaction"),
    "monnify.verify_transaction": ("GET", "/api/v2/merchant/transactions/query"),
    "monnify.create_reserved_account": ("POST", "/api/v2/bank-transfer/reserved-accounts"),
    "monnify.create_invoice": ("POST", "/api/v1/invoice/create"),
    "monnify.initiate_transfer": ("POST", "/api/v2/disbursements/single"),
    "monnify.bulk_transfer": ("POST", "/api/v2/disbursements/batch"),
    "monnify.query_transfer_status": ("GET", "/api/v2/disbursements/single/summary"),
    "monnify.validate_bank_account": ("GET", "/api/v1/disbursements/account/validate"),
    "monnify.transaction_split": ("POST", "/api/v1/split-transactions/split"),
    "monnify.initiate_refund": ("POST", "/api/v1/refunds/initiate-refund"),
}

_HEADER = '''"""{name} - generated by Monnify Studio.

Deterministic codegen from your flow graph (#146): no LLM wrote this file,
the same flow always generates the same code. Each function is one block on
your whiteboard. run() executes the trigger's chain in graph order; every
webhook becomes its own handle_* you mount on a route (never called inline).

Sandbox first: set MONNIFY_API_KEY / MONNIFY_SECRET_KEY / MONNIFY_CONTRACT_CODE
in your environment. Base URL defaults to the sandbox; change it only when you
have tested end to end.
"""

from __future__ import annotations

import base64
import os
import uuid
from decimal import Decimal

import httpx

BASE_URL = os.getenv("MONNIFY_BASE_URL", "https://sandbox.monnify.com")
CONTRACT_CODE = os.getenv("MONNIFY_CONTRACT_CODE", "")


class GuardFailed(Exception):
    """A safety block said no. Money must NOT move past this point."""


def _token(client: httpx.Client) -> str:
    """Authenticate (docs: https://developers.monnify.com/api/#authentication)."""
    basic = base64.b64encode(
        f"{{os.getenv('MONNIFY_API_KEY', '')}}:{{os.getenv('MONNIFY_SECRET_KEY', '')}}".encode()
    ).decode()
    resp = client.post(
        f"{{BASE_URL}}/api/v1/auth/login",
        headers={{"Authorization": f"Basic {{basic}}"}},
    )
    resp.raise_for_status()
    return resp.json()["responseBody"]["accessToken"]
'''


def _identifier(node: Node) -> str:
    """A stable python function name for a node."""
    raw = re.sub(r"[^a-z0-9_]+", "_", node.id.lower()).strip("_") or "block"
    if raw[0].isdigit():
        raw = f"n_{raw}"
    return raw


def _reachable(workflow: Workflow, start: str) -> list[Node]:
    """Nodes reachable from `start` in graph order (the engine's walk, #8)."""
    order: list[Node] = []
    seen: set[str] = set()
    adjacency: dict[str, list[str]] = {}
    for edge in workflow.edges:
        adjacency.setdefault(edge.source, []).append(edge.target)
    queue: deque[str] = deque([start])
    while queue:
        node_id = queue.popleft()
        if node_id in seen:
            continue
        seen.add(node_id)
        order.append(workflow.node(node_id))
        queue.extend(adjacency.get(node_id, []))
    return order


def _docstring(node: Node, catalog: Catalog) -> str:
    try:
        d = catalog.resolve(node.type)
    except KeyError:
        return f'    """{node.label or node.type}."""'
    lines = [f'    """{node.label or d.title} ({node.type}).']
    if d.when_to_use:
        lines += ["", f"    When to use: {d.when_to_use}"]
    if d.doc_url:
        lines += ["", f"    Docs: {d.doc_url}"]
    lines.append('    """')
    return "\n".join(lines)


def _config_literal(node: Node) -> str:
    if not node.config:
        return "{}"
    inner = ", ".join(f'"{k}": {v!r}' for k, v in node.config.items())
    return "{" + inner + "}"


def _num(value: object) -> float:
    try:
        return float(str(value))
    except (TypeError, ValueError):
        return 0.0


def _cfg(node: Node, *keys: str, default: object = "") -> object:
    for key in keys:
        if key in node.config and node.config[key] not in (None, ""):
            return node.config[key]
    return default


def _rows_literal(node: Node) -> list[str]:
    """Turn the Employee List sheet into a real Monnify batch transactionList,
    baked into the generated code so a Run actually pays those people."""
    rows = node.config.get("rows")
    rows = rows if isinstance(rows, list) else []
    lines = [
        "    # The people this flow pays, straight from your sheet. Edit freely.",
        '    ctx["transactionList"] = [',
    ]
    for i, row in enumerate(rows):
        if not isinstance(row, dict):
            continue
        name = str(row.get("name") or f"Payee {i + 1}")
        acct = str(row.get("account_number") or row.get("destinationAccountNumber") or "")
        bank = str(row.get("bank_code") or row.get("destinationBankCode") or "")
        lines.append(
            "        {"
            f'"amount": {_num(row.get("amount")):g}, '
            '"reference": f"pay-{uuid.uuid4().hex[:10]}", '
            f'"narration": {("Salary - " + name)!r}, '
            f'"destinationBankCode": {bank!r}, '
            f'"destinationAccountNumber": {acct!r}, '
            '"currency": "NGN"},'
        )
    lines += ["    ]", "    return ctx"]
    return lines


def _body(node: Node) -> list[str]:
    """The function body for one block. Config the dev typed rides along."""
    t = node.type
    if t == "app.data_rows":
        return _rows_literal(node)
    if t == "monnify.bulk_transfer":
        return [
            "    # One batch pays everyone on the sheet (up to 5,000 in a call).",
            "    body = {",
            f'        "title": {_cfg(node, "title", default="Payroll")!r},',
            '        "batchReference": f"batch-{uuid.uuid4().hex[:12]}",',
            f'        "narration": {_cfg(node, "narration", default="Bulk payout")!r},',
            '        "sourceAccountNumber": os.getenv("MONNIFY_WALLET", ""),',
            '        "onValidationFailure": "CONTINUE",',
            '        "notificationInterval": 10,',
            '        "transactionList": ctx.get("transactionList", []),',
            "    }",
            '    resp = client.post(',
            '        f"{BASE_URL}/api/v2/disbursements/batch",',
            '        headers={"Authorization": f"Bearer {token}"},',
            "        json=body,",
            "    )",
            "    resp.raise_for_status()",
            '    ctx.update(resp.json().get("responseBody") or {})',
            "    return ctx",
        ]
    if t == "monnify.initiate_transfer":
        return [
            "    # Move money to one beneficiary.",
            "    body = {",
            '        "amount": float(ctx.get("amount", 0)),',
            '        "reference": f"xfer-{uuid.uuid4().hex[:12]}",',
            f'        "narration": {_cfg(node, "narration", default="Payout")!r},',
            "        \"destinationBankCode\": "
            f"{_cfg(node, 'destination_bank_code', 'destinationBankCode')!r},",
            "        \"destinationAccountNumber\": "
            f"{_cfg(node, 'destination_account_number', 'destinationAccountNumber')!r},",
            '        "sourceAccountNumber": os.getenv("MONNIFY_WALLET", ""),',
            '        "currency": "NGN",',
            "    }",
            '    resp = client.post(',
            '        f"{BASE_URL}/api/v2/disbursements/single",',
            '        headers={"Authorization": f"Bearer {token}"},',
            "        json=body,",
            "    )",
            "    resp.raise_for_status()",
            '    ctx.update(resp.json().get("responseBody") or {})',
            "    return ctx",
        ]
    if t == "monnify.query_transfer_status":
        return [
            "    # Confirm the disbursement's real status (never trust a timeout).",
            '    resp = client.get(',
            '        f"{BASE_URL}/api/v2/disbursements/single/summary",',
            '        headers={"Authorization": f"Bearer {token}"},',
            '        params={"reference": ctx.get("reference", "")},',
            "    )",
            "    resp.raise_for_status()",
            '    ctx.update(resp.json().get("responseBody") or {})',
            "    return ctx",
        ]
    if t == "monnify.validate_bank_account":
        return [
            "    # Name Enquiry: confirm each account before a kobo moves.",
            '    resp = client.get(',
            '        f"{BASE_URL}/api/v1/disbursements/account/validate",',
            '        headers={"Authorization": f"Bearer {token}"},',
            '        params={',
            '            "accountNumber": ctx.get("destinationAccountNumber", ""),',
            '            "bankCode": ctx.get("destinationBankCode", ""),',
            "        },",
            "    )",
            "    resp.raise_for_status()",
            '    ctx.update(resp.json().get("responseBody") or {})',
            "    return ctx",
        ]
    if t in _ENDPOINTS:
        method, path = _ENDPOINTS[t]
        call = "client.get" if method == "GET" else "client.post"
        payload = "params" if method == "GET" else "json"
        return [
            f"    body = {{**{_config_literal(node)}, **ctx}}",
            '    body.setdefault("contractCode", CONTRACT_CODE)',
            f'    resp = {call}(',
            f'        f"{{BASE_URL}}{path}",',
            '        headers={"Authorization": f"Bearer {token}"},',
            f"        {payload}=body,",
            "    )",
            "    resp.raise_for_status()",
            '    ctx.update(resp.json().get("responseBody") or {})',
            "    return ctx",
        ]
    if t == "safety.verify_signature":
        return [
            "    # Verify the webhook came from Monnify before trusting a kobo of it.",
            "    import hashlib, hmac",
            '    secret = os.getenv("MONNIFY_SECRET_KEY", "").encode()',
            '    expected = hmac.new(secret, raw_payload, hashlib.sha512).hexdigest()',
            '    if not hmac.compare_digest(expected, signature_header):',
            '        raise GuardFailed("webhook signature mismatch: not Monnify")',
            "    return ctx",
        ]
    if t == "safety.validate_amount":
        return [
            "    # Paid must cover expected, compared exactly - never with floats.",
            f'    expected = Decimal(str(ctx.get("expected_amount", {node.config.get("expected_amount", 0)!r})))',
            '    paid = Decimal(str(ctx.get("amountPaid", ctx.get("paid_amount", "0"))))',
            "    if paid < expected:",
            '        raise GuardFailed(f"underpaid: {paid} of {expected}")',
            "    return ctx",
        ]
    if t == "safety.idempotency_guard":
        return [
            "    # Process each payment reference exactly once.",
            '    ref = ctx.get("paymentReference") or ctx.get("payment_reference")',
            "    if ref in _SEEN_REFERENCES:",
            '        raise GuardFailed(f"duplicate delivery: {ref} already handled")',
            "    _SEEN_REFERENCES.add(ref)",
            "    return ctx",
        ]
    if t == "safety.balance_guard":
        return [
            "    # Check the wallet covers the payout BEFORE moving money (MON012).",
            '    resp = client.get(f"{BASE_URL}/api/v2/disbursements/wallet-balance",',
            '                      headers={"Authorization": f"Bearer {token}"},',
            '                      params={"accountNumber": os.getenv("MONNIFY_WALLET", "")})',
            "    resp.raise_for_status()",
            '    balance = Decimal(str(resp.json().get("responseBody", {}).get("availableBalance", "0")))',
            '    amount = Decimal(str(ctx.get("amount", "0")))',
            "    if balance < amount:",
            '        raise GuardFailed(f"insufficient balance: {balance} < {amount}")',
            "    return ctx",
        ]
    if t.startswith("safety."):
        return [
            "    # Guard checkpoint: keep this before any money-moving call.",
            "    return ctx",
        ]
    if t.startswith("event."):
        return [
            "    # Webhook/event handler stub: mount this on your framework's route",
            "    # (e.g. POST /monnify/webhook) and pass the parsed payload in.",
            "    ctx.update(payload or {})",
            "    return ctx",
        ]
    if t == "custom.code":
        code = str(node.config.get("code", "")).rstrip()
        if code:
            snippet = ["    # --- your code block (verbatim from the whiteboard, #147) ---"]
            snippet += [f"    {line}" if line.strip() else "" for line in code.splitlines()]
            snippet += ["    # --- end code block ---", "    return ctx"]
            return snippet
        return [
            "    # Code Block: put your logic here. Read/modify ctx and return it.",
            "    return ctx",
        ]
    if t.startswith("app.notify"):
        return [
            "    # Tell the customer / your team. Swap print() for your own",
            "    # WhatsApp or email provider.",
            "    paid = len(ctx.get(\"transactionList\", [])) or 1",
            f'    message = {_cfg(node, "message", "text", default="Payment confirmed with Monnify.")!r}',
            '    print(f"[notify] {message} ({paid} recipient(s))")',
            "    return ctx",
        ]
    # app.* and anything else: a plain step that records what it did.
    return [
        f'    ctx.setdefault("log", []).append("{node.label or t}")',
        "    return ctx",
    ]


def generate_python(workflow: Workflow, catalog: Catalog | None = None) -> str:
    """The whole module: header, one function per block, and wiring that matches
    the graph - the entrypoint chain runs in run(); every other event root (a
    webhook) becomes its own handler you mount on a route, never called inline."""
    catalog = catalog or default_catalog()
    roots = [workflow.entrypoint] if workflow.entrypoint else []
    roots += [r for r in workflow.roots() if r not in roots]
    entry = roots[0] if roots else (workflow.nodes[0].id if workflow.nodes else None)

    spine = _reachable(workflow, entry) if entry else []
    emitted: set[str] = {n.id for n in spine}

    handler_chains: list[tuple[Node, list[Node]]] = []
    for root in roots[1:]:
        if root in emitted:
            continue
        chain = [n for n in _reachable(workflow, root) if n.id not in emitted]
        if not chain:
            continue
        emitted.update(n.id for n in chain)
        handler_chains.append((workflow.node(root), chain))

    orphans = [n for n in workflow.nodes if n.id not in emitted]

    parts: list[str] = [_HEADER.format(name=workflow.name)]
    parts.append("_SEEN_REFERENCES: set[str] = set()\n")

    def _emit_fn(node: Node) -> None:
        fn = _identifier(node)
        signature = f"def {fn}(ctx: dict, *, client: httpx.Client, token: str, "
        if node.type == "safety.verify_signature":
            signature += "raw_payload: bytes = b'', signature_header: str = '', "
        if node.type.startswith("event."):
            signature += "payload: dict | None = None, "
        signature = signature.rstrip(", ") + ") -> dict:"
        parts.append("\n".join(["", signature, _docstring(node, catalog), *_body(node)]))

    for node in spine:
        _emit_fn(node)
    for _root, chain in handler_chains:
        for node in chain:
            _emit_fn(node)
    for node in orphans:
        _emit_fn(node)

    spine_calls = [
        f"        ctx = {_identifier(n)}(ctx, client=client, token=token)" for n in spine
    ]
    body: list[str] = [
        "",
        "",
        "def run() -> dict:",
        f'    """Run the flow from its trigger, in graph order: {workflow.name}."""',
        "    ctx: dict = {}",
        "    with httpx.Client(timeout=30.0) as client:",
        "        token = _token(client)",
        *(spine_calls or ["        pass  # nothing on the entrypoint spine"]),
        "    return ctx",
    ]

    for root, chain in handler_chains:
        steps = [n for n in chain if not n.type.startswith("event.")]
        calls = [
            f"        ctx = {_identifier(n)}(ctx, client=client, token=token)" for n in steps
        ]
        body += [
            "",
            "",
            f"def handle_{_identifier(root)}(payload: dict) -> dict:",
            f'    """Mount on your webhook route (POST /monnify/webhook): '
            f'{root.label or root.type}."""',
            "    ctx: dict = dict(payload or {})",
            "    with httpx.Client(timeout=30.0) as client:",
            "        token = _token(client)",
            *(calls or ["        pass"]),
            "    return ctx",
        ]

    body += ["", "", 'if __name__ == "__main__":', "    print(run())", ""]
    parts.append("\n".join(body))
    return "\n".join(parts)
